apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.example.com  # Replace with your desired name
spec:
  group: example.com  # Replace with your desired group
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field1:
                  type: string
               field2:
                  type: integer
  scope: Namespaced  # or Cluster
  names:
    plural: myresources  # Plural name for the resource
    singular: myresource  # Singular name for the resource
    kind: MyResource  # Kind of the resource
    shortNames:
      - mr  # Short name for the resource